# Generated by Django 4.0.4 on 2022-08-16 13:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=500)),
                ('phone', models.CharField(default='', max_length=13)),
                ('message', models.TextField(default='', max_length=10000)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
