# Generated by Django 4.1 on 2022-08-17 23:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_moedig', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uploaded_file', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['png', 'pdf'])])),
            ],
        ),
    ]
