# Generated by Django 4.0.4 on 2022-08-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_moedig', '0005_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uploaded_file',
            field=models.FileField(upload_to=''),
        ),
    ]
