# Generated by Django 4.1 on 2022-08-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_moedig', '0011_order_delivery_status_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(default='holy gucamoli', max_length=1000),
        ),
    ]
