# Generated by Django 4.1 on 2022-08-21 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_moedig', '0012_alter_order_delivery_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='product_json',
            field=models.CharField(default='', max_length=20000),
            preserve_default=False,
        ),
    ]
