# Generated by Django 4.1 on 2022-08-21 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_moedig', '0013_remove_order_product_order_product_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(related_name='ordered_products', to='web_moedig.product'),
        ),
    ]
