# Generated by Django 4.1 on 2022-08-21 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_moedig', '0015_rename_product_order_producti_product_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='producti',
        ),
    ]
