# Generated by Django 4.1 on 2022-08-21 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_moedig', '0017_alter_order_payment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='order',
            new_name='order_id',
        ),
    ]
