# Generated by Django 4.1 on 2022-08-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_moedig', '0020_alter_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bill',
            field=models.FloatField(),
        ),
    ]
