# Generated by Django 4.1 on 2022-08-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_moedig', '0022_alter_order_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.DateField(auto_now_add=True),
        ),
    ]
