# Generated by Django 4.1 on 2022-08-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_moedig', '0025_alter_order_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('Order Placed', 'Order Placed'), ('Order Printed', 'Order Printed'), ('Order Shipped', 'Order Shipped'), ('Order Picked', 'Order Picked')], default='Order Placed', max_length=1000),
        ),
    ]
