# Generated by Django 4.1 on 2022-08-31 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_moedig', '0028_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='discount',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
