# Generated by Django 4.1 on 2022-09-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_moedig', '0029_coupon_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=2000)),
                ('message', models.CharField(max_length=20000)),
            ],
        ),
    ]
